### ISSUE TITLE
Recently stopped getting location and flag icon

### ISSUE THREAD

**Issue by charlwillia6** [PrimaMateria/ip-indicator_mint#1]
I have been using IP indicator with Cinnamon on Manjaro for sometime now, and recently, within the last two days, I updated my 15.09 stable version of Manjaro and IP indicator has now stopped getting location information and the flag icon for my country.  I have tried uninstalling it, reinstalling it, removing the applet from the panel, etc., and nothing changes the outcome.  I am not sure what stopped IP indicator from working, but there was no new changes to Cinnamon when I updated my distro the other day.  When you hover over the tray icon, you just get "trying to fetch IP information".  Clicking on the icon still gives you the IP address, but does not display the location.

**Comment by PrimaMateria** [comment]
Could be something wrong with the applet itself, could be something wrong with the service it calls to get the IP information. Anyway the service it uses currently announced that is ending on 15th November. [Here is why](http://www.cambus.net/adventures-in-running-a-free-public-api/).

Therefore next thing is that I need to find some suitable replacement. I will also add option in the settings to turn on debug mode, which will output some useful information to the logs. After the new version will be finished and it will be still not working for you, I will ask you to get the logs and hopefully it will be easier to deliver fix for your issue.

Subscribe to the repository notifications here on github if you want to get information about the changes.

**Comment by PrimaMateria** [comment]
Please update to new version and let me know if you still have this issue. If yes, please follow the steps from troubleshooting section.

**Comment by charlwillia6** [comment]
Perfect.  Icons, flags, and IP updates seem to work perfectly.  Thanks for working on this so quickly!
